# Generated by Django 3.2.14 on 2022-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0002_emploi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi',
            name='category',
            field=models.CharField(choices=[], default='doem', max_length=300),
        ),
    ]
