# Generated by Django 3.2.14 on 2022-09-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0003_alter_emploi_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi',
            name='category',
            field=models.CharField(choices=[('DOEM', 'DOEM'), ('DSPE', 'DSPE'), ('DSEPE', 'DSEPE')], default='doem', max_length=300),
        ),
    ]
