# Generated by Django 3.2.14 on 2022-09-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_auto_20220920_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='resume',
        ),
    ]
