# Generated by Django 3.2.14 on 2022-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0004_auto_20220920_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='presentation',
            field=models.TextField(null=True),
        ),
    ]
