# Generated by Django 3.2.14 on 2022-09-15 11:36

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_budget_etatbudget_planpassation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(choices=[('matrices activites', 'matrices activites')], default='budget', max_length=300, on_delete=django.db.models.fields.related.ForeignKey, related_name='budgets', to='documents.category'),
        ),
    ]
