# Generated by Django 3.2.14 on 2022-09-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_budget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('matrices activites', 'matrices activites'), ('projets programmes', 'projets programmes')], default='budget', max_length=300),
        ),
    ]
