# Generated by Django 3.2.14 on 2022-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_budget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('matrices activites', 'matrices activites'), ('projets programmes', 'projets programmes'), ('etat execution budget', 'etat execution budget'), ('plan de passation', 'plan de passation'), ('marches publiques passes', 'marches publiques passes'), ('etat execution marche publique', 'etat execution marche publique'), ('marches programmes', 'marches programmes'), ('resultats marches publiques', 'resultats marches publiques'), ('biens services contrats', 'biens services contrats'), ('bilan financiers', 'bilan financiers'), ('dons et legs', 'dons et legs'), ('comptes rendus', 'comptes rendus'), ('rapports annuels', 'rapports annuels'), ('rapports audits', 'rapports audits'), ('arretes decisions deliberations', 'arretes decisions deliberations'), ('marches etudes', 'marches etudes'), ('rapports statistiques', 'rapports statistiques'), ('formulaires procedures', 'formulaires procedures'), ('prestations services', 'prestations services'), ('plans actions', 'plans actions'), ('budget', 'budget'), ('documents juridiques', 'documents juridiques')], default='budget', max_length=300),
        ),
    ]
