# Generated by Django 3.2.14 on 2022-09-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgt', '0002_travail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travail',
            name='category',
            field=models.CharField(choices=[('DRT', 'DRT'), ('DIT', 'DIT'), ('DLTE', 'DLTE'), ('DSST', 'DSST')], default='doem', max_length=300),
        ),
    ]
