# Generated by Django 3.2.14 on 2022-09-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_generale', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(blank=True, max_length=1000)),
                ('titre', models.CharField(max_length=1000)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=1000)),
                ('resume', models.CharField(max_length=1000)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('category', models.CharField(choices=[], default='doem', max_length=300)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
    ]
