# Generated by Django 3.2.14 on 2022-09-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgps', '0002_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='category',
            field=models.CharField(choices=[('DPPH', 'DPPH')], default='doem', max_length=300),
        ),
    ]
