# Generated by Django 3.2.14 on 2022-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgps', '0003_alter_social_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='category',
            field=models.CharField(choices=[('DPPH', 'DPPH'), ('DAS', 'DAS'), ('DSSM', 'DSSM')], default='doem', max_length=300),
        ),
    ]
